services:
    app:
        container_name: sample-app
        image: python:3.12-slim
        command: sh -c "pip install flask prometheus_client && python app.py"
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - "8080:8080"

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: ["--config.file=/etc/prometheus/prometheus.yml"]

    grafana: 
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
