kind: Service
apiVersion: v1
metadata:
  name: bookapp-fe
spec:
  selector:
    app: bookapp-fe
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  # type: LoadBalancer # Change to LoadBalancer for Service. Lecture 62
  type: ClusterIP # Change to ClusterIP for Ingress. Lecture 63