name: AutoBuild lecture 13

on:                  # events that trigger the workflow
  push:              # push event
    branches:        # branches to trigger the workflow
      - main         # branches to trigger the workflow
    paths:           # paths to the files that trigger the workflow
      - 13/multi/**  # path to the directory with the Dockerfile 
  workflow_dispatch: # allows to run workflow manually

jobs:
    build:
        runs-on: ubuntu-latest
        run: 
          working-directory: 13/multi   
        steps:
            - uses: actions/checkout@v6
            - name: Build
              run: docker build -t serpent/ca-devops-ua6:v0.20 .
            - name: Login
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Push
              run: docker push serpent/ca-devops-ua6:v0.20
