name: 46. AWS SAM CI/CD

on:
  push:
    branches: [ "main" ]
    paths: 
      - "46/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: 46/cars
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::034362059178:role/github-actions-role-${{ github.event.repository.name }}
          aws-region: eu-central-1

      - name: Build SAM application
        run: sam build --use-container

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
